### PR TITLE
Ceph changes

### PR DESCRIPTION
**Pull request by mbruzek**
I will try to fix Ceph again.

These are the changes we discussed in #rhos-scale on Feb 27 2018.

@jeremyeder PTAL

### CODE REVIEW

**Comment by jtaleric** [comment]
Can you squash these into a single commit

**Comment by jeremyeder** [comment]
Based on IRC conversation, this looks good for another try.

**Comment by jtaleric** [comment]
Also according to Ben it is recommended not to use clock.redhat.com
So change the deploy command to use :
openstack overcloud deploy --templates -e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml -e templates/network-environment.yaml -e templates/deploy.yaml -e /usr/share/openstack-tripleo-heat-templates/environments/puppet-pacemaker.yaml -r templates/roles_data.yaml --ntp-server clock.redhat.com -e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml -e templates/network-environment.yaml -e templates/deploy.yaml -e /usr/share/openstack-tripleo-heat-templates/environments/puppet-pacemaker.yaml -r templates/roles_data.yaml --ntp-server clock1.rdu2.redhat.com
￼

**Comment by mbruzek** [comment]
I was just fixing the typo we do not use clock.redhat.com

**Pull request merged**
