### PR TITLE
Adding roles_data-notelem.yaml that disables telemetry.

### PR DESCRIPTION
**Pull request by jmencak**
Disabling telemetry by default for openshift-scalelab-ci.

### CODE REVIEW

**Comment by jtaleric** [comment]
Only suggestion I would have is to create a roles_data-notelem.yaml - that way, you can eventually look at deploying with telem?

**Comment by jmencak** [comment]
Added "OS::TripleO::Services::PankoApi", thanks!  Not so sure about adding roles_data-notelem.yaml.  I don't want to add a nearly identical duplicate yaml.

**Comment by jmencak** [comment]
I the above just a suggestion, @jtaleric? Or do you insist on splitting the roles_data.yaml.  I'd like to test this on a new deploy tomorrow.  Thx.

**Comment by jmencak** [comment]
Thank you for the suggestion, @jtaleric!

**Comment by mbruzek** [comment]
When linked with: https://github.com/redhat-performance/tripleo-quickstart-scalelab/pull/11 this PR get my +1

**Comment by akrzos** [comment]
If I am not mistaken, just disabling the services and not turning off publishing notifications/messaging you can end up crashing the messaging bus service.  I'll dig into this a bit more but I would expect we need to disable that publishing as well otherwise performance and stability may suffer later in the cloud.

**Comment by mbruzek** [comment]
Thanks for the response @akrzos . Please let me know if anything else needs to be done, we do not wish to crash the message service or have any more problems in the future.

**Comment by akrzos** [comment]
I believe your going to need 
```
parameter_defaults:
  NotificationDriver: 'noop'
```
but I'm unsure of this parameter's success or if you'll have an issue in your environment.  If you have some sort of rabbitmq monitoring you can see if stale messages are accruing in your message bus faster than they are expiring but I'm not sure at which point you'd see an issue or if you won't see an issue until you put enough load on the openstack cluster anyway.

**Pull request merged**
